name: Deploy Lambda

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install dependencies
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install -r app/requirements.txt
      - name: Check if function exists
        id: check_function
        run: |
          aws lambda get-function --function-name my-function || echo "::set-output name=function_exists::false"
          echo "::set-output name=function_exists::true"
      - name: Update or Create Lambda function code
        run: |
          cd app
          zip -r function.zip .
          if ${{ steps.check_function.outputs.function_exists }} == 'true'; then
            aws lambda update-function-code \
              --function-name my-function \
              --zip-file fileb://function.zip
          else
            aws lambda create-function \
              --function-name my-function \
              --zip-file fileb://function.zip \
              --handler app.lambda_handler \
              --runtime python3.8 \
              --role arn:aws:iam::731628207007:role/authentication
          fi
