name: Deploy Lambda

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: alpine-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 

    - name: Clone Lambda Repository
      run: |
        git clone https://github.com/renanhsilva/code-lambda-aws-teste
      env:
        GIT_TERMINAL_PROMPT: 0

    - name: Install Lambda Dependencies
      run: |
        cd code-lambda-aws-teste
        pip install -r requirements.txt 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Deploy Lambda
      run: |
        cd code-lambda-aws-teste
        zip -r lambda.zip .
        aws lambda create-function --function-name lambda-autenticacao --runtime python3.9 --role arn:aws:iam::731628207007:role/authentication --handler index.handler --zip-file fileb://lambda.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
