name: Deploy Lambda

on:
  push:
    branches:
      - infra

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configuração das credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalando as depedências
        run: |
          python -m venv venv
          source venv/bin/activate
        working-directory: ${{ github.workspace }}

      - name: Criando pacote das Lambdas
        run: |
          zip -r lambda_generate_token.zip  ./generate_token
          zip -r lambda_check_token.zip ./check_token
        
      - name: Lambda generate_token
        id: create_generate_token_function
        run: |
          if aws lambda get-function --function-name generate_token; then
            aws lambda update-function-code \
            --function-name generate_token \
            --zip-file fileb://lambda_generate_token.zip
            echo "Function updated"
          else
            aws lambda create-function \
            --function-name generate_token \
            --zip-file fileb://lambda_generate_token.zip \
            --handler lambda_function.lambda_handler \
            --runtime python3.8 \
            --role arn:aws:iam::731628207007:role/authentication
            echo "Function created"
          fi

      - name: Lambda check_token
        id: create_check_token_function
        run: |
          if aws lambda get-function --function-name check_token; then
            aws lambda update-function-code \
            --function-name check_token \
            --zip-file fileb://lambda_check_token.zip
            echo "Function updated"
          else
            aws lambda create-function \
            --function-name check_token \
            --zip-file fileb://lambda_check_token.zip \
            --handler lambda_function.lambda_handler \
            --runtime python3.8 \
            --role arn:aws:iam::731628207007:role/authentication
            echo "Function created"
          fi