name: Deploy Lambda

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install dependencies
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install -r app/requirements.txt
      - name: Deploy Lambda function
        run: |
          cd app
          zip -r function.zip .
          aws lambda create-function \
            --function-name my-function \
            --runtime python3.8 \
            --handler lambda_function.lambda_handler \
            --zip-file fileb://function.zip